version: "3.7"

services:

  notifier-nginx:
    image: nginx:alpine
    container_name: notifier-nginx
    working_dir: /application
    volumes:
      - .:/application
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    expose:
      - 8082
    environment:
      - VIRTUAL_HOST=notifier.grocelivery.eu
      - SHELL=/bin/ash

  php-fpm:
    image: php:7.3-fpm
    container_name: notifier-php-fpm
    working_dir: /application
    volumes:
      - .:/application

networks:
  default:
    external:
      name: nginx_proxy
