version: "3.7"

services:

  webserver:
    image: nginx:alpine
    container_name: notifier-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    expose:
      - 8082
    environment:
      - VIRTUAL_HOST=notifier.grocelivery.eu
      - SHELL=/bin/ash
    depends_on:
      - php-fpm

  php-fpm:
    build: .docker/php
    container_name: notifier-php-fpm
    working_dir: /application
    volumes:
      - .:/application

  redis:
    image: redis
    container_name: notifier-redis
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    restart: always
    command:
      --requirepass ${REDIS_PASSWORD}

networks:
  default:
    external:
      name: nginx_proxy
